### ISSUE TITLE
gherkin syntax doesn't work in Jira version 8.20.1

### ISSUE THREAD

**Issue by chauhanhitendra** [siavashs/Prism#61] opened 2022-02-14 11:39 UTC
gherkin syntax doesn't work in Jira version 8.20.1

1. Go to any issue in Jira version 8.20.1
2. Edit description and following and save the issue.
{code:gherkin}

{code}

The description should be empty and no error, but there is an error. See screenshot.
![image](https://user-images.githubusercontent.com/85669390/153857710-b0b5c0e9-58a5-4bc4-9d7b-3f50034f5917.png)

**Comment by chauhanhitendra** [comment] 2022-02-18 13:02
Can someone advise how to solve this issue ?

**Comment by siavashs** [comment] 2022-02-22 12:59
This is duplicate of #57

**Closed by siavashs** 2022-02-22 12:59 UTC
Labels: bug
